# Generated by Django 3.0.2 on 2020-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200116_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='portal',
        ),
    ]
