# Generated by Django 3.0.2 on 2020-01-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_news_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='portal',
        ),
        migrations.DeleteModel(
            name='portal',
        ),
    ]
