# Generated by Django 3.0.2 on 2020-01-17 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_news_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
